spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://111.230.135.149:3306/es?useSSL=false
    username: root
    password: lijipeng
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    resources:
    add-mappings: false