spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://192.168.31.147:3306/test?useSSL=false
    username: root
    password: 12345678
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver